tap neovim/homebrew-neovim
install coreutils
install ctags
install diff-so-fancy
install docker
install git
install go
install htop
install https://raw.githubusercontent.com/choppsv1/homebrew-term24/master/tmux.rb
install hub
install jq
install neovim --HEAD
install python
install reattach-to-user-namespace
install saltstack
install shellcheck
install the_silver_searcher
install thefuck
install tig
install tree
install urlview
install watch
