install awscli
install caskroom/cask/brew-cask
install cmake
install ctags
install git
install heroku-toolbelt
install hub
install jq
install macvim
install mercurial
install mongodb
install postgresql
install python
install reattach-to-user-namespace
install saltstack
install homebrew/versions/swig304
install the_silver_searcher
install thefuck
install tig
install tmux
install tree
