#!/bin/bash
set -e

main() {
  echo "Updating ..."
  brew update
  echo "Upgrading ..."
  brew upgrade

  installed=$(brew list | tr " " "\n")
  while read -r line; do
    read -r -a args <<< "$line"
    if [ "${args[0]}" == install ]; then
      formula=${args[1]}
      found=false
      for each in $installed; do
        if [ "$each" == "$formula"  ]; then
          found=true
          break
        fi
      done
      if $found; then
        continue
      fi
    fi
    echo "brew $line"
    # shellcheck disable=SC2086
    brew $line
  done < Brewfile
}

main
