#!/usr/bin/env bash
set -e

# Install salt from source.
if ! command -v salt-call > /dev/null; then
  salt_dir=~/oss/salt
  if ! [ -d $salt_dir ]; then
    git clone git@github.com:saltstack/salt.git $salt_dir
  fi
  pip install -e $salt_dir
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export DIR

TEMPDIR=$(mktemp -d /tmp/XXXXXXXX)
mkdir -p "$TEMPDIR/etc/salt"
touch "$TEMPDIR/etc/salt/minion_id"
mkdir -p "$TEMPDIR/var/log/salt"
touch "$TEMPDIR/var/log/salt/minion"

cat << EOF > $TEMPDIR/minion
root_dir: $TEMPDIR/
pki_dir: $TEMPDIR/pki/minion
cachedir: $TEMPDIR/cache/minion
log_level: info
file_client: local
local: true
file_roots:
  base:
    - $DIR/salt
    - $DIR/sources
pillar_roots:
  base:
    - $DIR/salt/pillar
EOF

command="$1"
if [ -n "$command" ]; then
  shift
else
  command=state.highstate
fi

salt-call --retcode-passthrough -c "$TEMPDIR" "$command" "$@"
