#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export DIR

# Install salt from source.
if ! command -v salt-call > /dev/null; then
  salt_dir=~/oss/salt
  if ! [ -d $salt_dir ]; then
    git clone git@github.com:saltstack/salt.git $salt_dir
  fi
  pip install -e $salt_dir
fi

# Own /etc/salt.
owner="$(stat -c '%U' /etc/salt)"
if [[ "$owner" != "$USER" ]]; then
  echo "Chowning /etc/salt..."
  sudo chown -vR "$USER" /etc/salt
fi

# Configure salt
mkdir -p /etc/salt
cat << EOF > /etc/salt/minion
root_dir: /etc/salt/
log_level: info
file_client: local
local: true
file_roots:
  base:
    - $DIR/salt
    - $DIR/sources
pillar_roots:
  base:
    - $DIR/salt/pillar
EOF

command="$1"
if [ -n "$command" ]; then
  shift
else
  command=state.highstate
fi

salt-call --retcode-passthrough "$command" "$@"
