#!/usr/bin/env bash
# This script runs masterless salt-call using a temporary directory for
# configuration.
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export DIR

TEMPDIR=$(mktemp -d /tmp/XXXXXXXX)
mkdir -p "$TEMPDIR/etc/salt"
touch "$TEMPDIR/etc/salt/minion_id"
mkdir -p "$TEMPDIR/var/log/salt"
touch "$TEMPDIR/var/log/salt/minion"

cat << EOF > $TEMPDIR/minion
root_dir: $TEMPDIR/
pki_dir: $TEMPDIR/pki/minion
cachedir: $TEMPDIR/cache/minion
file_client: local
local: true
file_roots:
  base:
    - $DIR/salt
    - $DIR/sources
pillar_roots:
  base:
    - $DIR/salt/pillar
EOF

salt-call --retcode-passthrough -c "$TEMPDIR" "$@"
