live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = false

# Colors: everforest_light
[colors.primary]        # TOGGLE_LIGHT
background = "0xfff9e8" # TOGGLE_LIGHT
foreground = "0x5c6a72" # TOGGLE_LIGHT
[colors.normal]         # TOGGLE_LIGHT
black      = "0xeaf2eb" # TOGGLE_LIGHT
blue       = "0x3a94c5" # TOGGLE_LIGHT
cyan       = "0x35a77c" # TOGGLE_LIGHT
green      = "0x8da101" # TOGGLE_LIGHT
magenta    = "0xdf69ba" # TOGGLE_LIGHT
red        = "0xf85552" # TOGGLE_LIGHT
white      = "0x5c6a72" # TOGGLE_LIGHT
yellow     = "0xdfa000" # TOGGLE_LIGHT
[colors.bright]         # TOGGLE_LIGHT
black      = "0xeaf2eb" # TOGGLE_LIGHT
blue       = "0x3a94c5" # TOGGLE_LIGHT
cyan       = "0x35a77c" # TOGGLE_LIGHT
green      = "0x8da101" # TOGGLE_LIGHT
magenta    = "0xdf69ba" # TOGGLE_LIGHT
red        = "0xf85552" # TOGGLE_LIGHT
white      = "0x5c6a72" # TOGGLE_LIGHT
yellow     = "0xdfa000" # TOGGLE_LIGHT
[colors.cursor]         # TOGGLE_LIGHT
cursor     = "0x5c6a72" # TOGGLE_LIGHT
text       = "0xfff9e8" # TOGGLE_LIGHT

# Colors: nord
# [colors.primary]        # TOGGLE_DARK
# background = "0x2E3440" # TOGGLE_DARK
# foreground = "0xD8DEE9" # TOGGLE_DARK
# [colors.normal]         # TOGGLE_DARK
# black      = "0x3B4252" # TOGGLE_DARK
# blue       = "0x81A1C1" # TOGGLE_DARK
# cyan       = "0x8FBCBB" # TOGGLE_DARK
# green      = "0xA3BE8C" # TOGGLE_DARK
# magenta    = "0xB48EAD" # TOGGLE_DARK
# red        = "0xBF616A" # TOGGLE_DARK
# white      = "0xD8DEE9" # TOGGLE_DARK
# yellow     = "0xEBCB8B" # TOGGLE_DARK
# [colors.bright]         # TOGGLE_DARK
# black      = "0x616E88" # TOGGLE_DARK
# blue       = "0x81A1C1" # TOGGLE_DARK
# cyan       = "0x8FBCBB" # TOGGLE_DARK
# green      = "0xA3BE8C" # TOGGLE_DARK
# magenta    = "0xB48EAD" # TOGGLE_DARK
# red        = "0xBF616A" # TOGGLE_DARK
# white      = "0xD8DEE9" # TOGGLE_DARK
# yellow     = "0xEBCB8B" # TOGGLE_DARK
# [colors.cursor]         # TOGGLE_DARK
# cursor     = "0xD8DEE9" # TOGGLE_DARK
# text       = "0x2E3440" # TOGGLE_DARK

# Cursor
[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 15

[font.bold]
family = "Operator Mono SSm"
style = "Bold"

[font.italic]
family = "Operator Mono SSm"
style = "Book Italic"

[font.normal]
family = "Operator Mono SSm"
style = "Book"

[font.offset]
x = 0
y = 10

[font.glyph_offset]
x = 0
y = 0

# Keyboard bindings
[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

# Mouse
[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# Scrolling
[scrolling]
history = 10000

# Selection
[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>-/."

# Shell
[shell]
args = ["--login"]
program = "/opt/homebrew/bin/bash"

# Window
[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
