# Make sure the shell is interactive
case $- in
    *i*) ;;
    *) return ;;
esac

# Change directory with cd
shopt -s autocd
# Autocorrect fudged paths in cd calls
shopt -s cdspell
# Update the hash table properly
shopt -s checkhash
# Update columns and rows if window size changes
shopt -s checkwinsize
# Put multi-line commands onto one line of history
shopt -s cmdhist
# Include dotfiles in pattern matching
shopt -s dotglob
# Enable advanced pattern matching
shopt -s extglob
# Append rather than overwrite Bash history
shopt -s histappend
# Repeat the line on failed history expansion
shopt -s histreedit
# Repeat the expanded line on successful history expansion
shopt -s histverify
# Don't use Bash's builtin host completion
shopt -u hostcomplete
# Don't change newlines to semicolons in history
shopt -s lithist
# Don't warn me about new mail all the time
shopt -u mailwarn
# Ignore me if I try to complete an empty line
shopt -s no_empty_cmd_completion
# Use programmable completion, if available
shopt -s progcomp
# Warn me if I try to shift when there's nothing there
shopt -s shift_verbose
# Don't use PATH to find files to source
shopt -u sourcepath

# These options only exist since Bash 4.0-alpha
if ((BASH_VERSINFO[0] >= 4)) ; then

    # Autocorrect fudged paths during completion
    shopt -s dirspell
    # Enable double-starring paths
    shopt -s globstar

    # Warn me about stopped jobs when exiting; only if >=4.1 due to bug
    # <https://lists.gnu.org/archive/html/bug-bash/2009-02/msg00176.html>
    ((BASH_VERSINFO[1] >= 1)) && shopt -s checkjobs

    # Expand variables in directory completion; only available since 4.3
    ((BASH_VERSINFO[1] >= 3)) && shopt -s direxpand
fi

# Bash completion.
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
export BASH_COMPLETION_DIR # Give salt access
bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"

# Editor.
export EDITOR='nvim'

# History.
# Keep around INFINITE lines of history in file
export HISTFILESIZE=""
export HISTSIZE=""
# Erase duplicate commands and whitespace in history
HISTCONTROL=ignoreboth:erasedups
# Use a more compact format for the time builtin's output
TIMEFORMAT='real:%lR user:%lU sys:%lS'

# Pager
export PAGER="less -IM"

# Vi mode.
set -o vi
bind '"\C-p": previous-history'
bind '"\C-n": next-history'
bind '"\C-b": backward-char'
bind '"\C-f": forward-char'
bind '"\eb": backward-word'
bind '"\ef": forward-word'
bind '"\C-d": delete-char'
bind '"^W": backward-kill-word'
bind '"\C-a": beginning-of-line'
bind '"\C-e": end-of-line'

# Load startup files in ~/.bashrc.d.
for sh in "$HOME"/.bashrc.d/*.bash ; do
    [[ -e $sh ]] && source "$sh"
done
unset -v sh
