# vi: ft=sh

if [ -f ~/.bashrc ]; then
  # shellcheck source=/Users/zhsi/.bashrc
  . ~/.bashrc
fi
source '/Users/zhsi/go/src/github.com/lyft/blessclient/lyftprofile' # bless ssh alias

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

