#!/bin/bash
set -e

export TERM=xterm-color

# Source service_venv if it exists
if command -v service_venv > /dev/null; then
  . service_venv
fi

if [ -f /root/.bashrc ]; then
  . /root/.bashrc
fi

# Do not exit interactive shell on errors
set +e
